# Serveur HTTP
server.port=7071
server.host=127.0.0.1

# Base de données
database.path=./data/scanner.db

# NAPS2
#naps2.command=naps2.console.exe //windows
#naps2.command=naps2 console //linux
naps2.command=naps2.console.exe
naps2.timeout.seconds=300

# SANE
sane.command=scanimage
sane.timeout.seconds=300

# Stockage PDF
storage.base.path=./scans
storage.cleanup.enabled=false
storage.cleanup.days=30

# Logging
logging.level=INFO
logging.file.enabled=false
logging.file.path=./logs/scanner-agent.log

